# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    async def DetectTranscriptionEnd(self, transcription: str,
        baml_options: BamlCallOptions = {},
    ) -> bool:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.DetectTranscriptionEnd(transcription=transcription,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="DetectTranscriptionEnd", args={
                "transcription": transcription,
            })
            return typing.cast(bool, result.cast_to(types, types, stream_types, False, __runtime__))
    async def FarewellAgent(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.FarewellAgent(messages=messages,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="FarewellAgent", args={
                "messages": messages,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    async def PrelimAgent(self, messages: typing.List["types.Message"],activities: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.ReplyTool", "types.StopTool", "types.BookActivityTool", "types.SuggestActivityTool"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.PrelimAgent(messages=messages,activities=activities,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="PrelimAgent", args={
                "messages": messages,"activities": activities,
            })
            return typing.cast(typing.Union["types.ReplyTool", "types.StopTool", "types.BookActivityTool", "types.SuggestActivityTool"], result.cast_to(types, types, stream_types, False, __runtime__))
    async def RespondAgent(self, messages: typing.List["types.Message"],activities: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.ReplyTool", "types.StopTool"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.RespondAgent(messages=messages,activities=activities,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="RespondAgent", args={
                "messages": messages,"activities": activities,
            })
            return typing.cast(typing.Union["types.ReplyTool", "types.StopTool"], result.cast_to(types, types, stream_types, False, __runtime__))
    async def ToolSelectAgent(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.GetEventsTool", "types.CheckPlantDataTool", "types.RecallTool", typing_extensions.Literal[False]]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ToolSelectAgent(messages=messages,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="ToolSelectAgent", args={
                "messages": messages,
            })
            return typing.cast(typing.Union["types.GetEventsTool", "types.CheckPlantDataTool", "types.RecallTool", typing_extensions.Literal[False]], result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectTranscriptionEnd(self, transcription: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[bool, bool]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="DetectTranscriptionEnd", args={
            "transcription": transcription,
        })
        return baml_py.BamlStream[bool, bool](
          result,
          lambda x: typing.cast(bool, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(bool, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def FarewellAgent(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="FarewellAgent", args={
            "messages": messages,
        })
        return baml_py.BamlStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def PrelimAgent(self, messages: typing.List["types.Message"],activities: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.Union["stream_types.ReplyTool", "stream_types.StopTool", "stream_types.BookActivityTool", "stream_types.SuggestActivityTool"], typing.Union["types.ReplyTool", "types.StopTool", "types.BookActivityTool", "types.SuggestActivityTool"]]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="PrelimAgent", args={
            "messages": messages,"activities": activities,
        })
        return baml_py.BamlStream[typing.Union["stream_types.ReplyTool", "stream_types.StopTool", "stream_types.BookActivityTool", "stream_types.SuggestActivityTool"], typing.Union["types.ReplyTool", "types.StopTool", "types.BookActivityTool", "types.SuggestActivityTool"]](
          result,
          lambda x: typing.cast(typing.Union["stream_types.ReplyTool", "stream_types.StopTool", "stream_types.BookActivityTool", "stream_types.SuggestActivityTool"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.ReplyTool", "types.StopTool", "types.BookActivityTool", "types.SuggestActivityTool"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def RespondAgent(self, messages: typing.List["types.Message"],activities: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.Union["stream_types.ReplyTool", "stream_types.StopTool"], typing.Union["types.ReplyTool", "types.StopTool"]]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="RespondAgent", args={
            "messages": messages,"activities": activities,
        })
        return baml_py.BamlStream[typing.Union["stream_types.ReplyTool", "stream_types.StopTool"], typing.Union["types.ReplyTool", "types.StopTool"]](
          result,
          lambda x: typing.cast(typing.Union["stream_types.ReplyTool", "stream_types.StopTool"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.ReplyTool", "types.StopTool"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ToolSelectAgent(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.Union["stream_types.GetEventsTool", "stream_types.CheckPlantDataTool", "stream_types.RecallTool", bool], typing.Union["types.GetEventsTool", "types.CheckPlantDataTool", "types.RecallTool", typing_extensions.Literal[False]]]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ToolSelectAgent", args={
            "messages": messages,
        })
        return baml_py.BamlStream[typing.Union["stream_types.GetEventsTool", "stream_types.CheckPlantDataTool", "stream_types.RecallTool", bool], typing.Union["types.GetEventsTool", "types.CheckPlantDataTool", "types.RecallTool", typing_extensions.Literal[False]]](
          result,
          lambda x: typing.cast(typing.Union["stream_types.GetEventsTool", "stream_types.CheckPlantDataTool", "stream_types.RecallTool", bool], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.GetEventsTool", "types.CheckPlantDataTool", "types.RecallTool", typing_extensions.Literal[False]], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def DetectTranscriptionEnd(self, transcription: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetectTranscriptionEnd", args={
            "transcription": transcription,
        }, mode="request")
        return result
    async def FarewellAgent(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FarewellAgent", args={
            "messages": messages,
        }, mode="request")
        return result
    async def PrelimAgent(self, messages: typing.List["types.Message"],activities: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="PrelimAgent", args={
            "messages": messages,"activities": activities,
        }, mode="request")
        return result
    async def RespondAgent(self, messages: typing.List["types.Message"],activities: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="RespondAgent", args={
            "messages": messages,"activities": activities,
        }, mode="request")
        return result
    async def ToolSelectAgent(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ToolSelectAgent", args={
            "messages": messages,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def DetectTranscriptionEnd(self, transcription: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetectTranscriptionEnd", args={
            "transcription": transcription,
        }, mode="stream")
        return result
    async def FarewellAgent(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FarewellAgent", args={
            "messages": messages,
        }, mode="stream")
        return result
    async def PrelimAgent(self, messages: typing.List["types.Message"],activities: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="PrelimAgent", args={
            "messages": messages,"activities": activities,
        }, mode="stream")
        return result
    async def RespondAgent(self, messages: typing.List["types.Message"],activities: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="RespondAgent", args={
            "messages": messages,"activities": activities,
        }, mode="stream")
        return result
    async def ToolSelectAgent(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ToolSelectAgent", args={
            "messages": messages,
        }, mode="stream")
        return result
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))