# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectTranscriptionEnd(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> bool:
        result = self.__options.merge_options(baml_options).parse_response(function_name="DetectTranscriptionEnd", llm_response=llm_response, mode="request")
        return typing.cast(bool, result)

    def FarewellAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FarewellAgent", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def PrelimAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.ReplyTool", "types.StopTool", "types.BookActivityTool", "types.SuggestActivityTool"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="PrelimAgent", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.ReplyTool", "types.StopTool", "types.BookActivityTool", "types.SuggestActivityTool"], result)

    def RespondAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.ReplyTool", "types.StopTool"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RespondAgent", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.ReplyTool", "types.StopTool"], result)

    def ToolSelectAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.GetEventsTool", "types.CheckPlantDataTool", "types.RecallTool", typing_extensions.Literal[False]]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ToolSelectAgent", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.GetEventsTool", "types.CheckPlantDataTool", "types.RecallTool", typing_extensions.Literal[False]], result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectTranscriptionEnd(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> bool:
        result = self.__options.merge_options(baml_options).parse_response(function_name="DetectTranscriptionEnd", llm_response=llm_response, mode="stream")
        return typing.cast(bool, result)

    def FarewellAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FarewellAgent", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def PrelimAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.ReplyTool", "stream_types.StopTool", "stream_types.BookActivityTool", "stream_types.SuggestActivityTool"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="PrelimAgent", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.ReplyTool", "stream_types.StopTool", "stream_types.BookActivityTool", "stream_types.SuggestActivityTool"], result)

    def RespondAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.ReplyTool", "stream_types.StopTool"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RespondAgent", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.ReplyTool", "stream_types.StopTool"], result)

    def ToolSelectAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.GetEventsTool", "stream_types.CheckPlantDataTool", "stream_types.RecallTool", bool]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ToolSelectAgent", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.GetEventsTool", "stream_types.CheckPlantDataTool", "stream_types.RecallTool", bool], result)

    