# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (8)
# #########################################################################

class BookActivityTool(BaseModel):
    action_name: typing.Optional[str] = None
    activity: typing.Optional[str] = None

class CheckPlantDataTool(BaseModel):
    action_name: typing.Optional[str] = None

class GetEventsTool(BaseModel):
    action_name: typing.Optional[str] = None

class Message(BaseModel):
    role: typing.Optional[typing.Union[str, str, str]] = None
    content: typing.Optional[str] = None

class RecallTool(BaseModel):
    action_name: typing.Optional[str] = None
    search_phrase: typing.Optional[str] = None

class ReplyTool(BaseModel):
    action_name: typing.Optional[str] = None
    response: typing.Optional[str] = None

class StopTool(BaseModel):
    action_name: typing.Optional[str] = None
    response: typing.Optional[str] = None

class SuggestActivityTool(BaseModel):
    action_name: typing.Optional[str] = None
    description: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
