# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Action": types.Action,
    "stream_types.Action": stream_types.Action,

    "types.Message": types.Message,
    "stream_types.Message": stream_types.Message,

    "types.QueryPastConversationTool": types.QueryPastConversationTool,
    "stream_types.QueryPastConversationTool": stream_types.QueryPastConversationTool,

    "types.ReplyTool": types.ReplyTool,
    "stream_types.ReplyTool": stream_types.ReplyTool,

    "types.StopTool": types.StopTool,
    "stream_types.StopTool": stream_types.StopTool,


}