# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.BookActivityTool": types.BookActivityTool,
    "stream_types.BookActivityTool": stream_types.BookActivityTool,

    "types.CheckPlantDataTool": types.CheckPlantDataTool,
    "stream_types.CheckPlantDataTool": stream_types.CheckPlantDataTool,

    "types.GetEventsTool": types.GetEventsTool,
    "stream_types.GetEventsTool": stream_types.GetEventsTool,

    "types.Message": types.Message,
    "stream_types.Message": stream_types.Message,

    "types.RecallTool": types.RecallTool,
    "stream_types.RecallTool": stream_types.RecallTool,

    "types.ReplyTool": types.ReplyTool,
    "stream_types.ReplyTool": stream_types.ReplyTool,

    "types.StopTool": types.StopTool,
    "stream_types.StopTool": stream_types.StopTool,

    "types.SuggestActivityTool": types.SuggestActivityTool,
    "stream_types.SuggestActivityTool": stream_types.SuggestActivityTool,


}